
echo "🔐 Fix GitHub Authentication on VS Code Linux"
echo "============================================="

# Method 1: GitHub CLI (แนะนำ)
echo "📦 Method 1: Install GitHub CLI"
echo "------------------------------"
echo "# Install GitHub CLI"
echo "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
echo "sudo apt update"
echo "sudo apt install gh"
echo ""
echo "# Login GitHub CLI"
echo "gh auth login"
echo ""
echo "# Login VS Code"
echo "gh auth login --scopes repo,user:email,read:org"
echo ""

# Method 2: Personal Access Token
echo "📋 Method 2: Personal Access Token"
echo "----------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Generate new token (classic)"
echo "3. Select scopes: repo, user:email, read:org"
echo "4. Copy token"
echo "5. In VS Code: Ctrl+Shift+P -> GitHub: Sign in"
echo "6. Choose: Sign in with token"
echo "7. Paste token"
echo ""

# Method 3: SSH Key
echo "🔑 Method 3: SSH Key Setup"
echo "--------------------------"
echo "# Generate SSH key"
echo "ssh-keygen -t ed25519 -C \"your-email@example.com\""
echo ""
echo "# Add to SSH agent"
echo "eval \"\$(ssh-agent -s)\""
echo "ssh-add ~/.ssh/id_ed25519"
echo ""
echo "# Show public key (copy to GitHub)"
echo "cat ~/.ssh/id_ed25519.pub"
echo ""
echo "# Test connection"
echo "ssh -T git@github.com"
echo ""

# Method 4: Browser fallback
echo "🌐 Method 4: Browser Fallback"
echo "-----------------------------"
echo "1. In VS Code: Ctrl+Shift+P"
echo "2. Type: GitHub: Sign in"
echo "3. Choose: Sign in with browser"
echo "4. If browser doesn't open:"
echo "   - Copy URL from VS Code"
echo "   - Open on another device"
echo "   - Complete authentication"
echo "   - Enter code back in VS Code"
echo ""

echo "🎯 Recommended: Try Method 1 (GitHub CLI) first"
